### ISSUE TITLE
Bootstrap styles

### ISSUE THREAD

**Issue by Krato** [livewire-ui/spotlight#12]
Hello!

First again, thanks for this amazing tool!

I love tailwind but for an admin project I choose a Boostrap dashboard theme. How can I customize the style? Yes, I can use `include_css`. option. But This styles are failing for some views. 

Can be possible to add ids to the divs? Then we will be able to override the styles. Or, other idea?

Thank you!

**Comment by vinhais** [comment]
A good idea would be an option to publish the Spotlight view.

**Comment by PhiloNL** [comment]
You can publish the view if you want with `php artisan vendor:publish --tag=livewire-ui-spotlight-views`. Given the release is not 'stable' yet, be sure to keep track of any changes in new releases since the view may be modified.

I'll take a look and see if I can find a way to fix this. Adding id or class properties might be the way to go.
